### PR TITLE
Remove go get commands from Makefile to prevent go.mod file from chan…

### PR DESCRIPTION
**Pull request by seiferteric**
…ging. Change patching process

### CODE REVIEW

**Comment by macikgozwa** [comment]
Hi @seiferteric ,
This PR should solve the `go.mod` version issue. However, it is applying the patch on the `GOPATH` directory. I don't see an immediate problem with that but overall convention is to apply the patch under the `vendor` dir.

Did you consider using `go mod download  package@version`? It is essentially `go get` without updating `go.mod`

E.g. It limits the patch to the vendor dir only. 

```
$(GO_DEPS): go.mod $(PATCHES)
-       # FIXME temporary workaround for crypto not downloading..
-       $(GO) get golang.org/x/crypto/ssh/terminal@e9b2fee46413
-       $(GO) get github.com/openconfig/gnmi@d2b4e6a45802a75b3571a627519cae85a197fdda
        $(GO) mod vendor
-       $(MGMT_COMMON_DIR)/patches/apply.sh vendor
+       go mod download golang.org/x/crypto@v0.0.0-20191206172530-e9b2fee46413
        cp -r $(GOPATH)/pkg/mod/golang.org/x/crypto@v0.0.0-20191206172530-e9b2fee46413 vendor/golang.org/x/crypto
+       $(MGMT_COMMON_DIR)/patches/apply.sh vendor      
        chmod -R u+w vendor
        patch -d vendor -p0 <patches/gnmi_cli.all.patch
        touch $@
diff --git a/go.mod b/go.mod
index b5e4ca0..a771136 100644
--- a/go.mod
+++ b/go.mod
```

**Comment by seiferteric** [comment]
We had an internal discussion a couple weeks back about these build dependencies. I think the main problem is that we are patching dependencies during build time in the first place. Go build system does not really support this, we are just doing it in the Makefile. I think the proper way to handle these patched dependencies would actually be to fork the dependent repositories and host them. That way we can just import the forked/patched libraries as normal go dependencies in the go.mod file. What do you think about this approach instead? These are the repos I think we would need to fork:
github.com/openconfig/gnmi
github.com/openconfig/ygot
github.com/openconfig/goyang
github.com/antchfx/jsonquery
github.com/antchfx/xmlquery
github.com/antchfx/xpath
github.com/golang/glog
github.com/jipanyang/gnxi​

**Comment by macikgozwa** [comment]
I don't know which one is more idiomatic. But the forking approach would also require changes on `sonic-mgmt-common` and any other repo that depends on it. Hence it is bigger work.

**Comment by seiferteric** [comment]
As far as idiomatic, I think the forking method is better since currently we can not simply do "go install github.com/Azure/sonic-telemetry" for example because the patching process in the Makefile will not happen and thus the go build process will not succeed. As far as changing the sonic-mgmt-common, it will just be a matter of fixing the imports and removing the patching process from both Makefiles. I don't mind putting in PRs for doing this, but to do so, we will need to be able to host these forked repositories first. If this sounds okay, I would like to do it this way since I think it will totally solve these build dependency issues.

**Comment by macikgozwa** [comment]
Sounds good to me. But I am not sure about hosting the forked/patched repos @hui-ma @pra-moh  can give some input.

**Comment by seiferteric** [comment]
@macikgozwa Okay updated the PR with your suggested changes, seems to be building fine for me.

**Review by macikgozwa — APPROVED** [review]

**Pull request merged**
